name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: composer-dependencies-cache-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv, intl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Prepare Laravel Application
        run: |
            cp .env.example .env
            php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit
